// <auto-generated />
using CampWatch.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampWatch.Infrastructure.Migrations
{
    [DbContext(typeof(CampWatchDbContext))]
    [Migration("20260702202213_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("CampWatch.Infrastructure.Models.CampsitePreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HikingWeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LakeWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxNights")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinNights")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NudgeThresholdScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrivateWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RemoteWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiverWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchWindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WoodedWeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("CampWatch.Infrastructure.Models.CampsiteSearchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CampgroundName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckIn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckOut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReservable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CampsiteResults");
                });

            modelBuilder.Entity("CampWatch.Infrastructure.Models.OutingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Outings");
                });

            modelBuilder.Entity("CampWatch.Infrastructure.Models.SearchProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CampgroundIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SearchProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
