import type { CampsiteFacts } from '../types/camping';

export const PRIMITIVE_SITE: CampsiteFacts = {
  id: 1,
  campgroundName: 'Hocking Hills State Park',
  campgroundId: '458',
  provider: 'OhioStateParks',
  siteId: 'A-12',
  siteType: 'WALK_IN',
  siteTypeLabel: 'Walk-In',
  isReservable: true,
  loop: 'WALK-IN LOOP A',
  checkIn: '2026-07-10',
  checkOut: '2026-07-12',
  nights: 2,
  bookingUrl: 'https://ohiostateparks.reserveamerica.com/campsite/458',
  receivedAt: '2026-07-02T22:00:00Z',
  status: 'New',
  matchScore: 87,
};

export const ELECTRIC_SITE: CampsiteFacts = {
  id: 2,
  campgroundName: 'Salt Fork State Park',
  campgroundId: '612',
  provider: 'OhioStateParks',
  siteId: 'B-04',
  siteType: 'STANDARD_ELECTRIC',
  siteTypeLabel: 'Standard / Electric',
  isReservable: true,
  loop: 'LOOP B',
  checkIn: '2026-07-10',
  checkOut: '2026-07-13',
  nights: 3,
  bookingUrl: 'https://ohiostateparks.reserveamerica.com/campsite/612',
  receivedAt: '2026-07-02T22:01:00Z',
  status: 'New',
  matchScore: 52,
};

export const WOODED_SITE: CampsiteFacts = {
  id: 3,
  campgroundName: 'Wayne National Forest Campground',
  campgroundId: '1079',
  provider: 'RecreationDotGov',
  siteId: 'C-07',
  siteType: 'WOODED_NONELECTRIC',
  siteTypeLabel: 'Wooded / Non-electric',
  isReservable: false,
  loop: 'HEMLOCK RIDGE',
  checkIn: '2026-07-15',
  checkOut: '2026-07-18',
  nights: 3,
  bookingUrl: 'https://www.recreation.gov/camping/campsites/1079',
  receivedAt: '2026-07-02T22:02:00Z',
  status: 'Interested',
  matchScore: 95,
};

export const SPARSE_SITE: CampsiteFacts = {
  id: 4,
  campgroundName: 'Unknown Campground',
  campgroundId: '',
  provider: 'OhioStateParks',
  siteId: '',
  siteType: '',
  siteTypeLabel: '',
  isReservable: false,
  loop: undefined,
  checkIn: '2026-08-01',
  checkOut: '2026-08-02',
  nights: 1,
  bookingUrl: '',
  receivedAt: '2026-07-02T22:03:00Z',
  status: 'New',
  matchScore: 30,
};
